sources:
  - version: "1.20.x || 1.21.x" # All versions from 1.20 to 1.21 use the same Japanese translation
    outputs:
      - name: Furigana-v3+1.20-1.20.1
        pack_format: 15 # 1.20 and 1.20.1 have the same pack format

      - name: Furigana-v3+1.20.2-1.21
        pack_format: 16
        supported_formats: # `supported_formats` added in 1.20.2
          # prettier-ignore
          [
            16, 17, 18, 19, 20, 21,
            22, 24, 25, 26, 27, 28,
            29, 30, 31, 32, 33, 34,
          ]

furigana:
  # Combinators take one or more parsed words and provide a reading for them as a single word. They are used for
  # compound words that are not in the morphological analyzer's dictionary, or for words whose dictionary reading is
  # unsuitable for their in-game meaning.
  # ! The keys must never partially intersect a parsed word
  combinators:
    つぶやく声: つぶやくごえ
    正しく: ただしく
    長押し: ながおし
    一切れ: ひときれ
    一回: いっかい
    上半: じょうはん
    下半: かはん
    不可壊: ふかかい
    九生: きゅうしょう
    他: ほか
    修飾子: しゅうしょくし
    剥いだ: はいだ
    召雷: しょうらい
    土: つち
    黄土色: おうどいろ
    真珠色: しんじゅいろ
    青緑色: せいりょくしょく
    黄緑色: おうりょくしょく
    閃緑岩: せんりょくがん
    安心感: あんしんかん
    的の中心: まとのちゅうしん
    読み込み中: よみこみちゅう
    宝物: たからもの
    山形波: やまがたなみ
    島: しま
    嵌: は
    帯: おび
    彩釉: さいゆう
    感圧板: かんあつばん
    打ち金: うちがね
    金: きん
    金床: かなとこ
    採蜜: さいみつ
    日本: にほん
    暗視: あんし
    様に: ように
    氷樹: ひょうじゅ
    溶鉱: ようこう
    溺水: できすい
    石レンガ: いしれんが
    石化: せきか
    石工: いしく
    羊肉: ようにく
    自傷: じしょう
    行商人: ぎょうしょうにん
    釣り人: つりびと
    製錬: せいれん
    負: ふ
    鉄塊: てっかい
    鍛冶: かじ
    間: あいだ
    防具立て: ぼうぐたて
    蓄風: ちくふう
    重撃: じゅうげき

  # Supplements are for words that fail reading correlation (e.g. the reading of ヶ月 (かげつ) contains no け and would
  # fail).
  # ! The keys must correspond to only a single parsed word (combined words can also be used as keys)
  supplements:
    ヶ月: かげつ

  # Translation-specific combinators and/or supplements:
  overrides:
    block.minecraft.target:
      combinators:
        的: まと
    stat.minecraft.target_hit:
      combinators:
        的: まと
    mco.template.select.none:
      combinators:
        空: から
